### PR TITLE
Fix/comma containg branch name

### LINKED ISSUE #70: Bug with comma-containing branch names
**Describe the bug**

As the title says, branch names with commas in them do not work properly.

<br>

**What I've tried**

I performed `gh poi` after creating `feature/hogehoge,fugafuga` branch.
As a result, I got the Error like this:
```bash
$ gh poi
✕ Fetching pull requests... 
failed to run external command: git, args: [log --first-parent --max-count=30 --format=%H feature/hogehoge --]    
exit status 128
```

Next, I performed the commands in the error statement, and sure enough, an error occurred.
```bash
$ git log --first-parent --max-count=30 --format=%H feature/hogehoge  --  
fatal: bad revision 'feature/hogehoge'
```

I modified that command and changed the branch name to include the comma and after, and it now works without error:
```bash
$ git log --first-parent --max-count=30 --format=%H feature/hogehoge,fugafuga --    
026078fd294ea5d096566c3eb7666f02fe62e171
d86a46b05b5466e198cd7d1b5439fc1605b5e372
2c2b8bbfa260e2ba9a7ebc9252c7f9dbd8607518
6f00654706e4ed4f93b51b4be9da661cba240450
....
```
<br>

**My Environment**
- OS: Windows 11 Home (Version 22H2)
- gh version 2.14.3
- gh-poi v0.6.0

### PR DESCRIPTION
**Pull request by AsPulse**
close #70
- #70 

In getting branch, here:
https://github.com/seachicken/gh-poi/blob/b9f2295afad1e175d8cb5fffa20d1d17f083f94f/conn/command.go#L54-L60
The data was obtained in comma-separated format, as in the following: `HEAD,refName,objectName`

However, when obtaining the refNames, it was assumed to be "the second element of split by a comma", so the error occured with comma-contained branch name.

Therefore, I have modified it to use the comma-joined string of "excluding the first and last elements" as the refName. ( f373c6e4573423be4ec42bd240937fe96935c248 )

In addition,

```go
head := false
if headValue == "*" {
  head = true
}
```
I found this writing style a bit redundant,
```go
head := headValue == "*"
```
I have made this modification. ( 9965e37c74868a5536c55969a9822bb24c4c87da )

I am beginner of  Go, so apologies if there are any problems.

### CODE REVIEW

File: poi.go [hunk 1]
```diff
@@ -467,13 +467,14 @@ func toBranch(branchNames []string) []Branch {
 
 	for _, branchName := range branchNames {
 		splitedNames := strings.Split(branchName, ",")
-		head := false
-		if splitedNames[0] == "*" {
-			head = true
-		}
+
+		headValue := splitedNames[0]
+		refNameValue := strings.Join(splitedNames[1:len(splitedNames)-1], ",")
```
Comment (seachicken) [inline poi.go:472]: This approach will not work when the number of information to be retrieved with `--format` is increased to four (e.g. `--format=%(HEAD),%(refname:lstrip=2),%(objectname),%(whatever)`).
Another idea is to use `--format` to change to a delimiter such as a whitespace that cannot be used in branch names

Comment (AsPulse) [reply poi.go]: I was a little nervous about including spaces in the command line argument, so I changed it to use a colon, which is also not included in the branch name.

(You can check that you can't use colons with `man git-check-ref-format`, but also when I actually try to created it, it created a branch name with the colon part missing.)

ea56c1727bcde8cf48d3177ce817690174c6ba21

File: poi.go [hunk 2]
```diff
@@ -466,14 +466,15 @@ func toBranch(branchNames []string) []Branch {
...
+		splitedNames := strings.Split(branchName, ":")
+
+		headValue := splitedNames[0]
+		refNameValue := splitedNames[1]
+
+		head := headValue == "*"
 		results = append(results, Branch{
 			head,
-			splitedNames[1],
+			refNameValue,
```
Comment (seachicken) [inline poi.go:477]: The code has been simplified so that the `refNameValue` variable is not needed

File: poi.go [hunk 3]
```diff
@@ -466,14 +466,15 @@ func toBranch(branchNames []string) []Branch {
...
-		head := false
-		if splitedNames[0] == "*" {
-			head = true
-		}
+		splitedNames := strings.Split(branchName, ":")
+
+		headValue := splitedNames[0]
+		refNameValue := splitedNames[1]
+
+		head := headValue == "*"
```
Comment (seachicken) [inline poi.go:474]: Nice that the if statement is gone 🙂
I think this is better because the readability is not much different.

```suggestion
		head := splitedNames[0] == "*"
```

File: poi.go (hunk 1 above)
Comment (seachicken) [reply poi.go]: >I was a little nervous about including spaces in the command line argument

I think I can enclose `--formt` in quotation marks. But this alone doesn't seem to work. It seems like it would be good to make it a `:`.
`"--format='%(HEAD) %(refname:lstrip=2) %(objectname)'"`

**Comment by AsPulse** [comment]
Certainly, I removed the headValue, refNameValue variables, since there is no need to bother with them if we can retrieve the correct order in an array!

As for how to put a space in the command, I thought it would be better to choose this simpler method, since a colon would suffice! But it was a learning experience, so thank you!

**Comment by AsPulse** [comment]
Like headValues, refNameValues, I wonder if there is no problem to put the head variable in the initialization of the structure...? I thought so, so I modified it.
( 1fc15ce144543b99c0a1e991f52b7e6767bdb56f )

**Comment by seachicken** [comment]
Yes, I think it's simple and good 😃

**Comment by AsPulse** [comment]
Thank you for merging this! :)

**Comment by seachicken** [comment]
Thank you! I released it now https://github.com/seachicken/gh-poi/releases/tag/v0.6.1
