### PR TITLE
Fix remote merged branches can be deleted

### LINKED ISSUE #74: Merged branches that have not been pulled locally are not deleted
**Describe the bug**
1. `git switch -c issue1` then commits
2. `git push origin issue1`
3. create issue1 PR on GitHub
4. merge issue1 PR
5. `gh poi`
6. Issue 1 is not deleted when the branch being merged is not pulled locally

**Your Environment**
- OS: macOS Monterey
- gh (Check with `gh --version`): v2.14.7
- gh-poi (For gh v2.6+ check with `gh extension list`): v0.6.1

### PR DESCRIPTION
**Pull request by seachicken**
Fixes #74

### CODE REVIEW

File: conn/command.go [hunk 1]
```diff
@@ -59,9 +59,9 @@ func (conn *Connection) GetBranchNames() (string, error) {
 	return run("git", args)
 }
 
-func (conn *Connection) GetMergedBranchNames() (string, error) {
+func (conn *Connection) GetMergedBranchNames(remoteName string, branchName string) (string, error) {
 	args := []string{
-		"branch", "--merged",
+		"branch", "--merged", fmt.Sprintf("%s/%s", remoteName, branchName),
```
Comment (seachicken) [inline conn/command.go:64]: Check merged with HEAD by default if branch name is not specified
